# Generated by Django 5.1.2 on 2024-10-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='score1',
            new_name='py5test',
        ),
    ]
